<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Parameter</name>
   <tag></tag>
   <elementGuidId>b0a3335a-78bd-455b-a9fe-9866c99fef7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-33']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c057e7fb-6add-48c0-ad92-53bec0534beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c115-237</value>
      <webElementGuid>7ddc3d10-1a57-4a80-bfac-9a9c2b206441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-33</value>
      <webElementGuid>a58f1a83-3b48-4644-8c32-7c7e35f899ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Parameter</value>
      <webElementGuid>dd5cf32f-f336-4b7f-8743-bdda99a7701f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-33&quot;)</value>
      <webElementGuid>f133e563-34fb-4e3e-bb6b-b14cb068d8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-33']</value>
      <webElementGuid>0b7186ef-a377-4386-b684-c6e7abefe78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-32']/div/div</value>
      <webElementGuid>a15ab735-232f-44aa-a400-e0705f0c4f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing Fee Based On'])[1]/following::div[13]</value>
      <webElementGuid>c0f44e4d-eb02-4a44-b2cb-2e4d6131a8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges'])[2]/following::div[16]</value>
      <webElementGuid>10530028-0b79-4602-a8cd-236c183f89eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penal Interest Based On'])[1]/preceding::div[6]</value>
      <webElementGuid>fa15f744-6055-4b9c-81fa-7e008b13388b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div</value>
      <webElementGuid>5888abaa-6f8d-47e2-9cfd-e66ccea85a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-33' and (text() = 'Select Parameter' or . = 'Select Parameter')]</value>
      <webElementGuid>94b64838-2c3b-4bb9-9d94-8a8cc0ce6c88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
