<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum_mat-input-37</name>
   <tag></tag>
   <elementGuidId>1b7f7720-931b-4264-bf90-07ff26bba6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-37</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-37']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e738a211-4e5f-4ba6-ba27-51403b860fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>sanctionLimitMax</value>
      <webElementGuid>243521d6-e8f3-4c99-8512-c213bc7158e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Maximum limit</value>
      <webElementGuid>0282a30b-2e56-4f39-9fc9-044823549ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>appvalidations</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>6172e500-819d-4451-8b68-3717ec8393ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c64-107 ng-pristine ng-invalid cdk-text-field-autofill-monitored ng-touched</value>
      <webElementGuid>4ba6422d-7c26-41b0-bf14-8eb4a0e0d825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-37</value>
      <webElementGuid>3bb0c304-d1aa-49ee-9103-3373e86b1ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Enter Maximum limit</value>
      <webElementGuid>973a1505-145c-43f7-b7bd-092800975381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>97bac239-5c3e-4aba-8fdd-9064253bfb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-37&quot;)</value>
      <webElementGuid>1e7bf7a0-1e6d-4f99-bffb-fd94687e3741</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-37']</value>
      <webElementGuid>8af40da8-ac29-4d6a-b732-e2577a061da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-1']/div/div[3]/div[2]/div/div[2]/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>88ec43e9-14c1-41fa-a1cd-f2d4bc1222d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>ea1c5400-ac78-4738-ad36-b08a47b63f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Maximum limit' and @id = 'mat-input-37']</value>
      <webElementGuid>a65f116f-d50d-460d-9cfc-18274ef21e5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
