<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum_mat-input-36</name>
   <tag></tag>
   <elementGuidId>5bf4f64e-2a09-4187-b9c2-0ff24964b880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-36</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-36']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de6584c2-c6eb-4f14-839a-d4bee719157d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>sanctionLimitMin</value>
      <webElementGuid>9c00e8e9-1153-4b96-a120-f6f336b06068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter minimum limit</value>
      <webElementGuid>d50b8959-8ed2-46b5-8bc0-3f0324e87d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>appvalidations</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>14faf1c5-3317-4ba7-9129-71401eec9f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c64-106 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>e124c67f-efe6-4faa-a0fb-29c5402f8de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-36</value>
      <webElementGuid>941be024-6121-4f0a-84f7-ce563fc98832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Enter minimum limit</value>
      <webElementGuid>9054a818-7eae-425d-986c-930a11f558e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>820dbb58-72a0-4da0-b844-e284a2ec8b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-36&quot;)</value>
      <webElementGuid>3642dfb0-1846-49af-8dca-b4b213da4a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-36']</value>
      <webElementGuid>2fa3fe2f-080d-4592-b4a9-ebdd55678b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-1']/div/div[3]/div[2]/div/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>492be44e-15c7-4893-baee-3072d53a5433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>8ba65d46-40be-45c3-934c-136ace39828f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter minimum limit' and @id = 'mat-input-36']</value>
      <webElementGuid>70820dc1-1e1d-4574-a3a4-f9899f31787e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
