<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loan Offer Validity_mat-input-9</name>
   <tag></tag>
   <elementGuidId>8aaea359-07e3-48ab-aeb8-e848e9b89872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a293f250-c816-488b-be9f-f07de1f61009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Loan Offer Validity</value>
      <webElementGuid>54d90feb-83d1-4950-b2ec-dd03ed42c7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4a32e5c4-0d53-4e72-822c-34d635f75e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>loanOfferValidityValue</value>
      <webElementGuid>2501c4d4-b87d-47b1-a817-793e94bb91f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>appvalidations</name>
      <type>Main</type>
      <value>Number</value>
      <webElementGuid>b2ebd03e-1378-424a-82e8-20a062e7c913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c64-40 ng-untouched ng-pristine cdk-text-field-autofill-monitored ng-invalid</value>
      <webElementGuid>f3140772-1994-4a23-a587-abc5460b1b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-9</value>
      <webElementGuid>a9085e14-9d16-4e96-91ad-eedd3dcc8348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select Loan Offer Validity</value>
      <webElementGuid>296b5596-0fed-411f-90f5-a6ee9c77a234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eefa7b80-25db-49cf-855c-1bb903f46781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5eafa2c0-0199-4039-9e7a-4cca04e2c1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-9&quot;)</value>
      <webElementGuid>927f011e-6ed7-4afa-9a34-a522545f48f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-9']</value>
      <webElementGuid>5aad56f0-b1bc-42b9-b26d-187005eb8b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>75c04acd-7f3f-451d-bb20-64b27173bf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Select Loan Offer Validity' and @id = 'mat-input-9']</value>
      <webElementGuid>4e1cd6a7-dea7-4b0a-a3c2-6be8dbe374e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
