<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-expansion-panel-header_9 Overall Custom_cf156b</name>
   <tag></tag>
   <elementGuidId>a0437a3c-3c29-4c09-853d-21e7314ce9fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-expansion-panel-header-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-expansion-panel-header</value>
      <webElementGuid>d614b089-ae16-45e1-8626-bfb067ab4096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0313c5b1-deb2-463d-8b80-fa6eba96b9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-expansion-panel-header mat-focus-indicator ng-tns-c131-75 ng-tns-c130-74 mat-expansion-toggle-indicator-after ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>1e4b7326-977d-47d8-bce0-d4a50da8edef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-expansion-panel-header-8</value>
      <webElementGuid>bdaad6eb-f0cd-4199-a653-c7a9d2746c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ee96c72a-406f-4f25-a4d0-1d3be94eb8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>cdk-accordion-child-8</value>
      <webElementGuid>eb53a8c4-a373-46ab-919b-f924de8483fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6fe81cdb-eb5f-47e6-ba38-7f845d75d1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68f4e468-79e7-423b-800b-372ee82b2224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9 Overall Customer Concentration (%) Delete </value>
      <webElementGuid>e339b3e0-641f-4fc9-8ee4-7c5de6d361ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-8&quot;)</value>
      <webElementGuid>ed1df1e2-5d8f-4dc2-863b-a0bad20fb869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-8']</value>
      <webElementGuid>8dde910c-c006-44cf-8db3-15be18471754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-0']/div/div/div[2]/mat-accordion/mat-expansion-panel[9]/mat-expansion-panel-header</value>
      <webElementGuid>88827fda-1d98-4434-aa8c-e6ba6500beb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[2]/following::mat-expansion-panel-header[1]</value>
      <webElementGuid>b4f1bef1-7e4f-498b-be1d-829d6c0a5df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max'])[7]/following::mat-expansion-panel-header[1]</value>
      <webElementGuid>fbcc2c63-d6d5-4144-b03a-935cbf33e305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[9]/mat-expansion-panel-header</value>
      <webElementGuid>b6b0c326-0341-4adf-b023-4f63ce523b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id = 'mat-expansion-panel-header-8' and (text() = '9 Overall Customer Concentration (%) Delete ' or . = '9 Overall Customer Concentration (%) Delete ')]</value>
      <webElementGuid>bf6daf8b-b015-43fc-9446-638cfa3e34a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
