<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-expansion-panel-header_10 Borrowers Ave_a24663</name>
   <tag></tag>
   <elementGuidId>ff7bd4da-7d0d-4f31-b9cf-2a66641cf794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-expansion-panel-header-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-expansion-panel-header</value>
      <webElementGuid>dabcde32-105d-4722-8fcb-393f7116b059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8491d23a-1e68-4db3-901a-0a14ef936a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-expansion-panel-header mat-focus-indicator ng-tns-c131-77 ng-tns-c130-76 mat-expansion-toggle-indicator-after ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>d47b4d5f-c0ff-4787-b17d-7f318fc81fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-expansion-panel-header-9</value>
      <webElementGuid>184b3735-7fc9-4fdf-95df-f594f4b001cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0ebcbd47-580a-4f34-8146-e7c1e52a3036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>cdk-accordion-child-9</value>
      <webElementGuid>f65b5bff-8920-4300-bfb8-a27aa7c9adc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2f7d7c19-16f0-4ee8-b6ac-049f90692912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7a6a218d-641a-404f-9b89-b75ee97ab858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10 Borrower's Average GST Compliance Score (GCS) Delete </value>
      <webElementGuid>27cc4d6f-36fe-4ce0-af44-4516902bf68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-9&quot;)</value>
      <webElementGuid>270791ac-df9a-4900-a3a9-06f668acea8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-9']</value>
      <webElementGuid>f9648194-6be3-43c3-8bd6-22404cf0f3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-0']/div/div/div[2]/mat-accordion/mat-expansion-panel[10]/mat-expansion-panel-header</value>
      <webElementGuid>bd9243b3-ec11-4878-846b-10b20124036a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[4]/following::mat-expansion-panel-header[1]</value>
      <webElementGuid>c4c0bac6-5335-48db-b15d-5a1a82319f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max'])[8]/following::mat-expansion-panel-header[1]</value>
      <webElementGuid>3474ba2b-b0ea-404d-8d2d-41da3a4de578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[10]/mat-expansion-panel-header</value>
      <webElementGuid>30ab44c5-37e7-400d-b8b8-4a2d82f5d5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id = 'mat-expansion-panel-header-9' and (text() = concat(&quot;10 Borrower&quot; , &quot;'&quot; , &quot;s Average GST Compliance Score (GCS) Delete &quot;) or . = concat(&quot;10 Borrower&quot; , &quot;'&quot; , &quot;s Average GST Compliance Score (GCS) Delete &quot;))]</value>
      <webElementGuid>3e998c82-e038-47df-ad00-66b57e29f859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
