<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-expansion-panel-header_6 Presence of ca_7110d8</name>
   <tag></tag>
   <elementGuidId>3a94c5b5-bc5f-4afe-9e43-4863cbccb079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-expansion-panel-header-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-expansion-panel-header</value>
      <webElementGuid>efab2154-0946-4a53-b81c-16cb33dfc38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>744910e4-7c05-436b-94ff-582950ce50c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-expansion-panel-header mat-focus-indicator ng-tns-c131-69 ng-tns-c130-68 mat-expansion-toggle-indicator-after ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>3367d7b3-2f94-4685-bb7d-68c9f5b20320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-expansion-panel-header-5</value>
      <webElementGuid>098538a6-23c7-4d6b-872c-201ddb6b96c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6596c170-8fe9-49c3-8a3e-c59d940ebcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>cdk-accordion-child-5</value>
      <webElementGuid>149c94d9-5483-4a36-bba4-da61288bef78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f2add2aa-d371-4438-8b64-14fc7b30ac1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>54f5920f-8923-4193-b5f1-a321f94a184d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6 Presence of cash credit/ OD account Delete </value>
      <webElementGuid>a2ff654f-18f6-4dc0-9d6a-849b364fad1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-5&quot;)</value>
      <webElementGuid>2e090007-fc6b-4301-8452-1616b553690d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-5']</value>
      <webElementGuid>8fcda697-fe27-4437-9e6b-ef4d3fdd9a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-0']/div/div/div[2]/mat-accordion/mat-expansion-panel[6]/mat-expansion-panel-header</value>
      <webElementGuid>1f7dfa42-579b-4e96-9901-cf0281f6aacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number'])[2]/following::mat-expansion-panel-header[1]</value>
      <webElementGuid>939caaa2-9c3f-4130-9dfd-96044d970b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max'])[6]/following::mat-expansion-panel-header[1]</value>
      <webElementGuid>0ff8d5aa-d07b-4594-b094-f5ce016443f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[6]/mat-expansion-panel-header</value>
      <webElementGuid>3ef79a23-d2a1-4d80-bd85-cf730ddba81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id = 'mat-expansion-panel-header-5' and (text() = '6 Presence of cash credit/ OD account Delete ' or . = '6 Presence of cash credit/ OD account Delete ')]</value>
      <webElementGuid>7dcc9321-05ad-435b-83da-7eb99bca1b8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
