<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-expansion-panel-header_3 Aggregate DPD _afa108</name>
   <tag></tag>
   <elementGuidId>da760e77-35f0-42c8-b150-d7a0ad0cf25e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-expansion-panel-header-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-expansion-panel-header</value>
      <webElementGuid>11f9457f-b6a1-42e7-a564-052221b6f783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b462d832-8fc0-413f-96c2-b4697bcff269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-expansion-panel-header mat-focus-indicator ng-tns-c131-63 ng-tns-c130-62 mat-expansion-toggle-indicator-after ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>529908fb-76da-4f23-9630-6c90f2cd48c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-expansion-panel-header-2</value>
      <webElementGuid>745647e7-b2bb-4f76-b7a5-37a6ad75698a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2afbf8b7-8bfe-4d53-8c5e-287920d9d55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>cdk-accordion-child-2</value>
      <webElementGuid>2078bd15-6989-4a16-aaae-3cd16dde8f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>418ad2de-8c06-4a90-a602-e8140454fd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17ff854d-d58e-40a0-bf11-9f1152135cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3 Aggregate DPD (in days) - Commercial Bureau in last 12 months Delete </value>
      <webElementGuid>71daadc7-a6fa-4cbb-90dd-ff2ddea61aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-2&quot;)</value>
      <webElementGuid>b18408b4-5be2-474a-a14f-865b91190c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-2']</value>
      <webElementGuid>17c7e89d-3a3e-42cd-962e-645647350594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-0']/div/div/div[2]/mat-accordion/mat-expansion-panel[3]/mat-expansion-panel-header</value>
      <webElementGuid>b0cd65a3-57c5-409e-9c54-328f3db36355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[3]/mat-expansion-panel-header</value>
      <webElementGuid>479207d9-7ec9-4356-8fd8-33f6ca827c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id = 'mat-expansion-panel-header-2' and (text() = '3 Aggregate DPD (in days) - Commercial Bureau in last 12 months Delete ' or . = '3 Aggregate DPD (in days) - Commercial Bureau in last 12 months Delete ')]</value>
      <webElementGuid>9d04bb57-3199-4d4d-b9b8-988e0745899c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
