<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Not Required</name>
   <tag></tag>
   <elementGuidId>67b1f6e6-872b-42b6-ac31-13360cae186e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-95 > span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-95']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fe317f21-7b06-42e1-94a2-00cb353577e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>79fe3e22-bc6d-42c9-bcfb-04bf1e69977f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Required</value>
      <webElementGuid>e8ff42c6-a24b-4b59-a963-6bb88cd87389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-95&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>27946ced-c0ef-4a94-bdb5-143b0309855f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-95']/span</value>
      <webElementGuid>12fb0abe-f940-4250-a59b-a3fe2bcd76b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Borrower', &quot;'&quot;, 's Supplier', &quot;'&quot;, 's Average GCS')])[1]/following::span[1]</value>
      <webElementGuid>9111a147-6e2c-4b64-ad50-f9fcf711beac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Borrower', &quot;'&quot;, 's Average GCS')])[1]/following::span[2]</value>
      <webElementGuid>61a0f9bd-85f3-47d3-ac0c-9bba9a348dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Amount'])[1]/preceding::span[1]</value>
      <webElementGuid>e8ade1b6-a54b-4ab3-9f36-cab181e4878e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Not Required']/parent::*</value>
      <webElementGuid>dc8f96e8-cdab-4e4f-9fb2-5e555e4537d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[7]/span</value>
      <webElementGuid>c749031a-275a-4bc1-a9cc-6fecbd593c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Not Required' or . = 'Not Required')]</value>
      <webElementGuid>8318d123-9aa3-4801-a9d5-69a4c5affc64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
