<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_No_mat-slide-toggle-thumb</name>
   <tag></tag>
   <elementGuidId>cfe67ed3-754a-4c9b-86de-31616081174d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-slide-toggle-6 > label.mat-slide-toggle-label > span.mat-slide-toggle-bar > span.mat-slide-toggle-thumb-container > span.mat-slide-toggle-thumb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-slide-toggle[@id='mat-slide-toggle-6']/label/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db4d2f76-788b-42bf-8def-a5a1825fa04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-slide-toggle-thumb</value>
      <webElementGuid>f2f147aa-87e2-4a68-9f88-7ea1f277c4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-slide-toggle-6&quot;)/label[@class=&quot;mat-slide-toggle-label&quot;]/span[@class=&quot;mat-slide-toggle-bar&quot;]/span[@class=&quot;mat-slide-toggle-thumb-container&quot;]/span[@class=&quot;mat-slide-toggle-thumb&quot;]</value>
      <webElementGuid>a81fd5d9-21c6-4d42-be17-422925c1e027</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-slide-toggle[@id='mat-slide-toggle-6']/label/span/span/span</value>
      <webElementGuid>cae29659-244e-40c4-9255-d9507ccb3068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[7]/div/div/app-rang-input/div/ng-contaner/ng-contaner/div/div/div/div/mat-slide-toggle/label/span/span/span</value>
      <webElementGuid>32a657ad-b49f-497b-a4de-44387cfadac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
